server:
  port: 19091

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/products/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v1/deliveries/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/v1/companies/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hubs/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/v1/ai/**

        - id: alarm-service
          uri: lb://alarm-service
          predicates:
            - Path=/v1/alarms/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v1/auth/**
        # Swagger 문서용 라우팅
        - id: delivery-service-api-docs
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/api-docs/**
          filters:
            - RewritePath=/delivery-service/api-docs, /api-docs
        - id: company-service-api-docs
          uri: lb://company-service
          predicates:
            - Path=/company-service/api-docs/**
          filters:
            - RewritePath=/company-service/api-docs, /api-docs
        - id: hub-service-api-docs
          uri: lb://hub-service
          predicates:
            - Path=/hub-service/api-docs/**
          filters:
            - RewritePath=/hub-service/api-docs, /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: delivery-service
        url: /delivery-service/api-docs
      - name: hub-service
        url: /hub-service/api-docs
      - name: company-service
        url: /company-service/api-docs