server:
  port: 19400

spring:
  application:
    name: company-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.sparta.order-service: DEBUG
    org.hibernate.SQL: DEBUG